jobs:
  build1:
    docker:
      - image: cyversevice/jupyterlab-base:latest
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/jupyterlab-base:1.0.5
    steps:
      - checkout
      - run: jupyter lab --version
workflows:
  version: 2
  build1_and_build2:
    jobs:
      - build1
      - build2

